name: DevOps-GitHibActions
on: [push, pull_request]

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: cd frontend && npm install
      - name: Build Project
        run: cd frontend && CI=false npm run build
        env:
          CI: false
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./frontend/build
